### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by brillout** [s-kris/vite-ssr-next-auth#1]
How about a Readme that explains what `vite-ssr-next-auth` is about and how to use it?

I'll add `vite-ssr-next-auth` to the `vite-plugin-ssr` docs.

**Comment by s-kris** [comment]
Thank you :)
added readme. ref: 2226092ba3c5ba1de81107ffe1e5af7632c3420b

**Comment by brillout** [comment]
Perfect 👌

**Comment by brillout** [comment]
Added link to this repo https://github.com/brillout/vite-plugin-ssr/commit/8a316fadf3191d2af903e9977d1953e79b1b439e
